### ISSUE TITLE
Ability to manually replicate ECR image to different regions and use it in cyclone

### ISSUE THREAD

**Issue by jamie1911** [awslabs/aws-cyclone-solution#16]

**Comment by ludvn** [comment]
Latest pull request accepted. Thank you for contributing. Now if you put _REGION_ in an image_uri cyclone will replace that with the actual region code in each region and pull the local image. The other option to also use your own image is to create a generic cyclone image with "hyper images add-image". You can then use "hyper images replace-with-local-image" to replace cyclone images across all enabled regions with a local docker image.

**Comment by ludvn** [comment]
Can we close this issue now you think?
